// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSPNVcgguWjcUo4OUhb4159FRP6Mi6fSU',
    appId: '1:644035745569:web:83fd2ca5ad4307eeacd060',
    messagingSenderId: '644035745569',
    projectId: 'fitsync-login',
    authDomain: 'fitsync-login.firebaseapp.com',
    storageBucket: 'fitsync-login.firebasestorage.app',
    measurementId: 'G-G2Z1LG0TNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmpD4Q1fzgi90bBX_P89MrLAnWMNLKWP4',
    appId: '1:644035745569:android:9e3899e324940019acd060',
    messagingSenderId: '644035745569',
    projectId: 'fitsync-login',
    storageBucket: 'fitsync-login.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWKrjpiZZSp7ynxd_i9wCJj4TuHBHwLGg',
    appId: '1:644035745569:ios:fc100fbf7c10b977acd060',
    messagingSenderId: '644035745569',
    projectId: 'fitsync-login',
    storageBucket: 'fitsync-login.firebasestorage.app',
    iosBundleId: 'com.example.fitsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWKrjpiZZSp7ynxd_i9wCJj4TuHBHwLGg',
    appId: '1:644035745569:ios:fc100fbf7c10b977acd060',
    messagingSenderId: '644035745569',
    projectId: 'fitsync-login',
    storageBucket: 'fitsync-login.firebasestorage.app',
    iosBundleId: 'com.example.fitsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSPNVcgguWjcUo4OUhb4159FRP6Mi6fSU',
    appId: '1:644035745569:web:aa1981a12c9dd558acd060',
    messagingSenderId: '644035745569',
    projectId: 'fitsync-login',
    authDomain: 'fitsync-login.firebaseapp.com',
    storageBucket: 'fitsync-login.firebasestorage.app',
    measurementId: 'G-5RM80S2J89',
  );
}
